# -*- coding: utf-8 -*-
"""Salt_and_pepper_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18-e2kfdwo5aI9xJV-d1xlbl4AZylOjXE
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt


image_path = 'TC/12.png'
image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)


if image is None:
    raise ValueError("Image not loaded. Please check the path.")


pixel_values = image.flatten()
hist, bins = np.histogram(pixel_values, bins=256, range=[0, 255])


plt.figure(figsize=(20, 6))
plt.plot(hist, color='black')
plt.title('Histogram of Grayscale Image Pixel Intensity')
plt.xlabel('Pixel Intensity')
plt.ylabel('Frequency')
plt.xlim([0, 255])
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

def detect_salt_and_pepper_noise(image_path, salt_threshold=0.005, pepper_threshold=0.005):
    image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)


    rows, cols = image.shape


    salt_noise = ((image == 255) & (cv2.medianBlur(image, 3) == 0)).astype(int)
    num_salt_noise = np.sum(salt_noise)


    pepper_noise = ((image == 0) & (cv2.medianBlur(image, 3) == 255)).astype(int)
    num_pepper_noise = np.sum(pepper_noise)


    total_pixels = rows * cols
    salt_noise_ratio = num_salt_noise / total_pixels
    pepper_noise_ratio = num_pepper_noise / total_pixels

    print(f"Salt noise ratio: {salt_noise_ratio:.4f}")
    print(f"Pepper noise ratio: {pepper_noise_ratio:.4f}")


    plt.figure(figsize=(15, 5))
    plt.subplot(131), plt.imshow(image, cmap='gray')
    plt.title('Input Image'), plt.xticks([]), plt.yticks([])
    plt.subplot(132), plt.imshow(salt_noise, cmap='gray')
    plt.title('Salt Noise'), plt.xticks([]), plt.yticks([])
    plt.subplot(133), plt.imshow(pepper_noise, cmap='gray')
    plt.title('Pepper Noise'), plt.xticks([]), plt.yticks([])
    plt.show()


    salt_detected = salt_noise_ratio > salt_threshold
    pepper_detected = pepper_noise_ratio > pepper_threshold

    if salt_detected and pepper_detected:
        print("Salt and pepper noise detected")
        return True
    elif salt_detected:
        print("Salt noise detected")
        return True
    elif pepper_detected:
        print("Pepper noise detected")
        return True
    else:
        print("No significant salt and pepper noise detected")
        return False

